### ISSUE TITLE
효창공원-선린고 지름길 좀요!

### ISSUE THREAD

**Issue by qorwhddlrz** [sunrinio-org/QnA#140]
아직은 그냥 도로쪽으로 다니고있는데, 지름길 없을까요!

**Comment by dohvis** [comment]
지하주차장이요! 그 뒤에 숙대 지하주차장 가로지르면 바로 선린 후문 나올걸요? 차조심하세요 :)

**Comment by qorwhddlrz** [comment]
억 급하게 써서.. 효창공원입구역-선린고 지름길요!

**Comment by dohvis** [comment]
400번 버스타서 숙대 도서관에서 내리는거?.. 말곤 딱히 없는거같네요. 저는 네이버길찾기 나온 결과로 계속 다녔어요ㅋㅋ
