### ISSUE TITLE
신입생 컴퓨터 구매

### ISSUE THREAD

**Issue by wangseung** [sunrinio-org/QnA#15]
안녕하세요! 이제 막 들어온 신입생입니다ㅎㅎ 

전공과목이 많다고 해서 공부도 할겸 컴퓨터를 사려고 하는데요.
노트북이 좋을지 데스크톱이 좋을지 몰라 여쭤봅니다! 

괜찮은게 있다면 추천도 해주세요!

**Comment by junorouse** [comment]
https://www.facebook.com/groups/1468406833432096/

추천드립니다.
