### ISSUE TITLE
비추 신고기능은 없나요?

### ISSUE THREAD

**Issue by jen6** [sunrinio-org/QnA#24]
답변달았는데 비추 받아서 약간 불쾌하네요;

**Comment by nerogit** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by wookje** [comment]
해커톤은 즐거우셨나요?

**Comment by Leop0ld** [comment]
불쾌하십니까? 맞비추로 대응하세요 :)

**Comment by jen6** [comment]
다들 비추 하나씩 드리겠습니다

**Comment by junorouse** [comment]
@jen6 도와드렸읍니다 💃

**Comment by jen6** [comment]
@junorouse 비추 드렸습니다
