### ISSUE TITLE
이 게시판에 질문글이 아닌 답변글 써도 되나요?

### ISSUE THREAD

**Issue by sunrinio** [sunrinio-org/QnA#98]
익명이 필요할 것 같네요. 저격을 당할 것 같아서..

**Comment by stealstick** [comment]
그문제를 해결하기 위하여 선린이오 서비스가 현재 제작중입니다.
현재에는 임시로 깃허브 이슈를 사용하고 있으니 익명이 필요하시면 질문으로 해주셔도 무방할 것 같습니다^^.

**Comment by nerogit** [comment]
ask.sunrin.io 에다 제목: `99번 질문에 익명으로 답달아주세요` 하면 올려드릴께여
